import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter, JetBrains_Mono, Google_Sans } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import { BodyWrapper } from './bodyWrapper'
import { HeaderWrapper } from './headerWrapper'

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

const gSans = Google_Sans({
  subsets: ["latin"],
  variable: "--font-gsans",
  display: "swap",
});


export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <BodyWrapper className={`${inter.variable} ${jetBrainsMono.variable} ${gSans.variable} antialiased text-white`}>
          <Providers>
            <HeaderWrapper />
            {children}
          </Providers>
        </BodyWrapper>
      </html>
    </ClerkProvider>
  )
}
